version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-rest
    command: --init-file /data/init.sql
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
      - ./data/init.sql:/data/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=event_db
